CREATE TRIGGER trg_KOMISYONLAR_GUNCELLEME_TARIHI
ON komisyonlar
AFTER UPDATE
AS 
BEGIN

    SET NOCOUNT ON;

    IF (TRIGGER_NESTLEVEL(OBJECT_ID('trg_KOMISYONLAR_GUNCELLEME_TARIHI'), 'AFTER', 'DML') > 1) RETURN;

    UPDATE k
    SET k.guncellenme_tarihi = GETDATE()
    FROM komisyonlar k
    INNER JOIN inserted ins ON k.id = ins.id;
    

END;
GO
